"""Train/evaluate the commit-risk model on data/risk/commits.csv.

Usage:
    python scripts/train_risk_model.py

Outputs:
    models/risk_model.joblib       model bundle (both variants)
    data/risk/evaluation.json      full metrics
    data/risk/EVALUATION.md        human-readable summary
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import joblib  # noqa: E402
import pandas as pd  # noqa: E402

from app.config import PROJECT_ROOT  # noqa: E402
from app.risk.predictor import MODEL_PATH  # noqa: E402
from app.risk.train import train_all  # noqa: E402

DATA = PROJECT_ROOT / "data" / "risk"
METRIC_COLS = ["accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc"]


def _row(name: str, m: dict) -> str:
    cm = m["confusion_matrix"]
    vals = " | ".join("-" if m[c] is None else f"{m[c]:.3f}" for c in METRIC_COLS)
    return f"| {name} | {vals} | {cm['tn']}/{cm['fp']}/{cm['fn']}/{cm['tp']} |"


def markdown(report: dict) -> str:
    d = report["dataset"]
    lines = [
        f"# Commit Risk Model — Evaluation ({report['version']})",
        "",
        "Generated by `scripts/train_risk_model.py`. All numbers are computed on real CI",
        "outcomes mined from public GitHub repositories (see `mining_summary.json`).",
        "",
        f"- Rows: **{d['rows']}** commits from {len(d['repos'])} repos; overall failure rate "
        f"**{d['failure_rate']:.1%}**",
        f"- Split (temporal, per repo): {d['split_sizes']}; failure rate per split: "
        f"{d['split_failure_rates']}",
        "",
    ]
    header = "| Model | " + " | ".join(METRIC_COLS) + " | TN/FP/FN/TP |\n|---|" + "---|" * (len(METRIC_COLS) + 1)
    for variant, r in report["variants"].items():
        lines += [
            f"## Variant `{variant}` — chosen: **{r['chosen_model']}** ({r['selection']})",
            "",
            "### Test set (newest 20% of each repo)",
            "",
            header,
        ]
        for name, c in r["candidates"].items():
            lines.append(_row(name + (" ✅" if name == r["chosen_model"] else ""), c["test"]))
        for name, m in r["baselines_test"].items():
            lines.append(_row(f"*baseline:* {name}", m))
        lines += ["", "### Observed test failure rate by predicted risk level", "",
                  "| Level | Commits | Observed failure rate |", "|---|---|---|"]
        for lvl, v in r["test_failure_rate_by_risk_level"].items():
            rate = "-" if v["observed_failure_rate"] is None else f"{v['observed_failure_rate']:.1%}"
            lines.append(f"| {lvl} | {v['commits']} | {rate} |")
        lines += ["", "### Leave-one-repo-out (train on 8 repos, test on the unseen one)", "",
                  "| Repo | n | failure rate | ROC-AUC | PR-AUC |", "|---|---|---|---|---|"]
        for repo, v in r["leave_one_repo_out"].items():
            lines.append(f"| {repo} | {v['n']} | {v['failure_rate']:.1%} | {v['roc_auc']:.3f} | {v['pr_auc']:.3f} |")
        top = list(r["permutation_importance_val"].items())[:8]
        lines += ["", "### Top features (permutation importance, validation PR-AUC drop)", ""]
        lines += [f"- `{f}`: {v:.4f}" for f, v in top]
        lines.append("")
    lines += [
        "## Caveats",
        "",
        "- Labels are CI outcomes of each repo's test workflow, judged per job; jobs against",
        "  unreleased dependencies are ignored, and runs whose failed jobs never executed a step",
        "  or failed only in infra steps (checkout/setup/cache/upload) are dropped as ambiguous.",
        "  Residual noise (flaky tests, external outages) remains.",
        "- GitHub retains roughly one year of Actions history, which bounds the data per repo.",
        "- Risk levels are rank-based on validation scores (LOW < p50 <= MEDIUM < p85 <= HIGH);",
        "  the classification metrics use the validation F1-optimal threshold.",
        "- `diff_only` is the model used for commits without CI history (e.g. the demo sandbox).",
        "- Test-coverage change is not available from CI metadata and is not a feature.",
        "- Risk is an additional signal, not proof that a bug exists.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    df = pd.read_csv(DATA / "commits.csv")
    bundle, report = train_all(df)

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(bundle, MODEL_PATH, compress=3)
    (DATA / "evaluation.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    (DATA / "EVALUATION.md").write_text(markdown(report), encoding="utf-8")
    print(markdown(report))
    print(f"Saved model -> {MODEL_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
